### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by nyvelius** [chewbecky/wireframr#3]
Hi

Great idea behind the plugin. Unfortunately I can't seem to get it to work. Nothing seems to happen when pressing "Create wireframes".

**Steps to reproduce**

1. Download wireframr.sketchplugin and run it.
2. The plugin appears in the plugins menu under Wireframr.
3. Select elements on the screen and press "Create wireframes".

**Result**

Nothing happens. No error message or anything. No visible effect.

**Version**

Sketch 52.2 on macOS Big Sur

**Comment by chewbecky** [comment]
Hi, I am really sorry to hear you are having trouble with the plugin. It does seem to work fine for me, but I do have the latest sketch version. I guess that upgrading Sketch should fix your problem. If it does not, let me know!

**Comment by nyvelius** [comment]
I suppose it is getting a bit old... :) Thanks @chewbecky
